[project]
name = "code-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=2.10.4",
    "pendulum>=3.0.0",
    "requests>=2.32.3",
]
